### PR TITLE
Guide on startup bug

### PR DESCRIPTION
**Pull request by snoopyjoe**
Fix guide on startup setting. Bool setting was set to always true in globals.py which ignored settings.xml.

### CODE REVIEW

**Comment by snoopyjoe** [comment]
That's what I thought too, but I was getting default=true in the settings.xml regardless if the bool setting was ticked or not. Though I think that may just be how Kodi handles bool settings by keeping the default and ignoring it if there's a selected value. 

Switching of the ActivateWindow is probably all that's needed.

**Comment by d21spike** [comment]
My understanding is it's pulled in as a string. So the comparing is made to see if it matches "true" to get a Boolean value. Another way to look at it would be is the Boolean result will only be True if the string matches "true".

Now where the comparison is made should functionally make no difference except doing it in the globals now provides a Boolean to the rest of the add-on. Doing it else-where means you have to keep redoing the comparison so making more work in a sense.

So I guess my question is did moving the comparison give you better results?  
In terms of the change of order, activating the Home screen first and TVGuide second (conditionally) sort of negates the intended design. 
image
Basically this was added first not as a feature but as a fix then I realized it'd be nice to have a setting for it. The gist is currently the Sling add-on disables IPTV on shutdown and re-enables it after the Slinger service is running. This is to give the webserver with the guide a chance to launch first before IPTV starts to pull it in. With this happening, if it's the only PVR installed on start-up kodi would not give the option to view the guide since it thinks no PVR's are installed. I realized once you visit the Channels or Guide screen, Kodi realizes that a PVR is indeed installed. So the quick toggle to the guide and back home was added. Your reversal of the order breaks this fix since the guide window would only be brought up if the setting is enabled for start-up.

The actual setting value as specified in addon.xml is highlighted in the screenshot below
image
The default="true" would only have effect if no value was specified, hence default. If you look at the settings.xml definition file, the default is actually **false**.
image

**Comment by snoopyjoe** [comment]
The only problem is when the guide starts up it overrides any Kodi start up window. There isn't a real need to activate the home window but the way it's setup now is if the EPG to IPTV setting is enabled then the guide auto starts even when the "start guide on startup" setting false. Maybe it would be better if the function checked the setting instead of the global. The guide would start but then immediately after the home screen would open.
Another option would be to move the activate guide window to after the pvr is reenabled. That would give the add-on time to check the setting and see if it needs to display the guide or not.

**Comment by d21spike** [comment]
I think you're missing the point here bud. 

If only one PVR exists and Kodi starts with IPTV **disabled** then the TV Menu will not have a guide option, see below.
image
That was the whole point of adding this, to escape this issue. Now if this behavior is what you meant by a "bug" then I suppose you would be correct here to a degree. Otherwise, the behavior of redirection was by design to avoid that screen. @eracknaphobia noticed today when we were checking the setting we were not taking into account whether EPG injection was turned on or not. So that check will be added shortly.

I think you're getting hung up on the setting when it was in fact the desired behavior. 
- Guide On Startup **off**, the guide screen would flash but bring it back to Home. 
- Guide On Startup **on**, the guide screen remains displayed.

Your last suggestion is not quite possible for two reasons. 
- First, we need to the webserver to be running prior to IPTV so there is guide data to pull in. If the server isn't running then the guide will be blank. 
- Second, we have no flag or any way of directly communicating with the PVR. All we have are JSON rpc calls to enable/disable the PVR which if done during playback or guide execution led to Kodi crashing altogether. In perfect world, Kodi would have a function to toggle the PVR check for updates, unfortunately no such luck. In reality the python libraries for interfacing with the PVR are quite lacking.

At this point as far as I can see we can do one of the following...
1.  Turn off the guide screen flash altogether and only have it come up if the setting is enabled (I believe this is what you were after). It would get rid of the redirection but leave the TV menu as shown above.
2. Leave the PVR enabled and allow it to fail when trying to pull in data due to it launching before the webserver. This would result in a blank guide until the next scheduled PVR check.
3. Find another way to trigger the PVR to injest the data once it is ready. (So far we haven't had much luck.)

The earlier versions used actual files for the EPG but that also presented it's own issues of write lock so that's one of the advantages of the webserver.

**Comment by snoopyjoe** [comment]
Now I see said the blind man. That makes more since with the Guide On Startup explanation. Your option #4 would be ideal as it would allow the chosen Kodi startup window to still show. Right now I have Kodi start on "TV Channels" window but it becomes inaccessible with the addon because the TV guide or Home window become my only two options. I also have two PVRs so the empty PVR was never an issue. I'll dive into whether the chosen Kodi startup window can be pointed to and make a new PR.

**Comment by d21spike** [comment]
> Now I see said the blind man. That makes more since with the Guide On Startup explanation. Your option #4 would be ideal as it would allow the chosen Kodi startup window to still show. Right now I have Kodi start on "TV Channels" window but it becomes inaccessible with the addon because the TV guide or Home window become my only two options. I also have two PVRs so the empty PVR was never an issue. I'll dive into whether the chosen Kodi startup window can be pointed to and make a new PR.

Well that's also another option, popping open Channels achieves the same effect as the Guide window. Just figured the guide was a better choice. Ultimately, I was waiting for response to see how it was received so this is just the feedback I needed. Now, we just need an functional solution for both cases. Ultimately, this has been the biggest hurdle having no control over the Guide/PVR beyond providing guide data. This is a little better in Kodi 19 since IPTV allows you to set a refresh timeframe as low as 10 minutes, but you can't just abandon Kodi 18 users.

**Pull request closed without merging**
