### PR TITLE
Fix on-demand show (Amazing Mysteries) using different JSON parameters

### PR DESCRIPTION
**Pull request by xags**
PR to address an On-demand show (Amazing Mysteries) using a different parameter with the JSON payload under 'background_image' and 'thumbnail' than show.py is expecting.

Here is the JSON blob for a broken episode:
```javascript
{
    "airings": [{
        "ratings": [
            "US_MPAA_UR"
        ],
        "_href": "http://cbd46b77.cdn.cms.movetv.com/cms/publish3/asset/info/e57c565f7ebe44849e323ba6dd23deb8.json",
        "title": "Amazing Mysteries",
        "program_id": 2168738,
        "source_id": 1442,
        "vendor_content_id": "LLVAL014MAG_Bonus",
        "has_blackouts": false,
        "duration": 2909.01,
        "external_id": "e57c565f7ebe44849e323ba6dd23deb8",
        "availability": [{
                "channel_id": 1885,
                "channel_guid": "246b3ad254b34b0498682688d8fab675",
                "stop": "2030-07-11T03:59:00Z",
                "start": "2020-03-16T04:01:00Z",
                "availability_type": "svod",
                "qvt": "http://cbd46b77.cdn.cms.movetv.com/cms/publish3/entitlement/asset/efc89fb7371e4bfe9968495e6a684d50/e57c565f7ebe44849e323ba6dd23deb8.qvt"
            },
            {
                "channel_id": 1885,
                "channel_guid": "246b3ad254b34b0498682688d8fab675",
                "stop": "2030-07-11T03:59:00Z",
                "start": "2020-03-16T04:01:00Z",
                "availability_type": "svod",
                "qvt": "http://cbd46b77.cdn.cms.movetv.com/cms/publish3/entitlement/asset/2b51540c9ed84863804a037e73d940c6/e57c565f7ebe44849e323ba6dd23deb8.qvt"
            }
        ],
        "airing_id": 43933715
    }],
    "ratings": [
        "US_MPAA_UR"
    ],
    "background_image": {
        "url": "http://p-img.movetv.com/cms/images/bbe93e4711deffaf18e69997eb76f73c76fcf05a.jpg",
        "h": 1080,
        "credit_short": null,
        "w": 1920,
        "credit_full": null
    },
    "guid": "dbb2bfd7ff784a72aa901be16bfa8585",
    "description": "Dinosaurs became extinct 65 million years ago. Was it triggered by an asteroid impact? Global volcanic activity?  A worldwide flood? The fossil records show something different. What really happened?      ",
    "name": "Dinosaur Extinction: What Killed the Dinosaurs?",
    "thumbnail": {
        "url": "http://p-img.movetv.com/cms/images/bbe93e4711deffaf18e69997eb76f73c76fcf05a.jpg",
        "h": 1080,
        "credit_short": null,
        "w": 1920,
        "credit_full": null
    },
    "episode_number": 3,
    "type": "episode",
    "id": 2168738,
    "_href": "http://cbd46b77.cdn.cms.movetv.com/cms/api/programs/dbb2bfd7ff784a72aa901be16bfa8585"
```

Here is a working JSON blob:

```javascript
{
    "airings": [{
        "ratings": [
            "US_UPR_TV-G"
        ],
        "_href": "http://cbd46b77.cdn.cms.movetv.com/cms/publish3/asset/info/1a41eb1d985641a782a17fe16b9d1756.json",
        "title": "Adopt",
        "program_id": 2505612,
        "source_id": 1603,
        "vendor_content_id": "DOGP0000000000009163",
        "has_blackouts": false,
        "duration": 294.53,
        "external_id": "1a41eb1d985641a782a17fe16b9d1756",
        "availability": [{
                "channel_id": 1467,
                "channel_guid": "de24cb792ce14252860ef3a7e1ab6fad",
                "stop": "2024-05-06T03:59:59Z",
                "start": "2020-05-05T04:01:00Z",
                "availability_type": "svod",
                "qvt": "http://cbd46b77.cdn.cms.movetv.com/cms/publish3/entitlement/asset/6fb84893343d4ee89ebadb45d0c5d605/1a41eb1d985641a782a17fe16b9d1756.qvt"
            },
            {
                "channel_id": 2056,
                "channel_guid": "354260716fd4486d9dd4cd979fb02cac",
                "stop": "2024-05-06T03:59:59Z",
                "start": "2020-05-05T04:01:00Z",
                "availability_type": "svod",
                "qvt": "http://cbd46b77.cdn.cms.movetv.com/cms/publish3/entitlement/asset/d9184b7fece64017b1cb25cf4d246979/1a41eb1d985641a782a17fe16b9d1756.qvt"
            }
        ],
        "airing_id": 49518559
    }],
    "ratings": [
        "US_UPR_TV-G"
    ],
    "background_image": {
        "h": 1440,
        "href": "http://p-img.movetv.com/cms/images/31c326b6eed9d77597dac322221fee7c6035671b.jpg",
        "credit_short": null,
        "w": 2560,
        "credit_full": null
    },
    "guid": "d0e557969fb84b1599a0757cb9ac04d4",
    "description": "DOGTV is working with rescues across the US to get dogs adopted. Adopt a dog now and get a great adoption kit. Season 2 episode 23",
    "name": "Adopt S02E23",
    "thumbnail": {
        "h": 1440,
        "href": "http://p-img.movetv.com/cms/images/31c326b6eed9d77597dac322221fee7c6035671b.jpg",
        "credit_short": null,
        "w": 2560,
        "credit_full": null
    },
    "episode_number": 23,
    "type": "episode",
    "id": 2505612,
    "_href": "http://cbd46b77.cdn.cms.movetv.com/cms/api/programs/d0e557969fb84b1599a0757cb9ac04d4"
}
```

If there is a better way to do this, please let me know.

### CODE REVIEW

**Comment by d21spike** [comment]
@xags I will incorporate the changes from your commit 54e2dd9 since it addresses a case where url's can be missing. Unfortunately you coupled this pull request with commit 83d6395 which not only replaces many things unnecessarily but also contains sensitive information I suggest you remove.
image

I appreciate the help on this.

**Comment by xags** [comment]
Well that was a stupid mistake, I clearly committed to the wrong repo for the second commit ID (pulled out just the slinger service is why there is so much changed/havoc). I deleted the fork so I'm not sure how I can remove the second commit... I tried pulling the PR and rebasing and undoing the commit and pushing, but obviously I don't have access to commit that.

**Comment by d21spike** [comment]
@xags I wouldn't stress it too much, just change your password and you should be good. Might get a bit more spam for a while.

**Comment by d21spike** [comment]
Issue addressed in commit 8ab383e, closing.

**Pull request closed without merging**
